### ISSUE TITLE
Webpack 4 upgrade task list

### ISSUE THREAD

**Issue by hubcarl** [hubcarl/easywebpack#13]
- [x] webpack-tool 依赖的 Webpack 升级 webpack4
- [x]  插件 webpack-manifest-resource-plugin 支持 webpack4
- [ ]  插件 vue-ssr-dynamic-chunk-plugin 支持 webpack4
- [x] easywebpack config 合并改造，采用数组push，然后合并
- [x] easywebpack 移除历史兼容代码
- [x] easywebpack 和 egg-webpack publicPath proxy 改造, 静态资源与项目同域访问
- [x] easywebpack 升级 eslint-loader: 2.0.0
- [x] easywebpack 升级 file-loader:1.1.10
- [x] easywebpack-vue 升级 vue-loader: 14.1.1
- [x] easywebpack 升级 extract-text-webpack-plugin： 4.0.0-alpha.0
- [x] webpack-hot-middleware 插件hack支持 webpack4
- [x] commonsChunk 改造支持 splitChunks 和 runtimeChunk
- [x] 解决热更新无效,  module.hot 始终是 false 问题
- [x] service worker 相关插件改造和问题问题
- [x] easywebpack webpack4 单元测试
- [x] easywebpack-vue webpack4 单元测试
- [x] easywebpack-react webpack4 单元测试
- [x] easywebpack webpack4 支持 4.0.0 发布
- [x] easywebpack-vue webpack4 支持 4.0.0 发布
- [x] easywebpack-react webpack4 支持 4.0.0 发布
- [x] easywebpack-html webpack4 支持 4.0.0 发布
- [x] easywebpack-js webpack4 支持 4.0.0 发布
- [x] Vue Client Render 骨架升级
- [x] React Client Render 骨架升级
- [x] Egg + Vue SSR 骨架升级
- [x] Egg + React SSR 骨架升级
- [x] easywebpack-cli 升级
- [x] 相关项目升级
